// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "study/Transaction/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Deposit mocks base method.
func (m *MockRepository) Deposit(arg0 context.Context, arg1 model.DepositParams) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", arg0, arg1)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deposit indicates an expected call of Deposit.
func (mr *MockRepositoryMockRecorder) Deposit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockRepository)(nil).Deposit), arg0, arg1)
}

// GetTransactionDetails mocks base method.
func (m *MockRepository) GetTransactionDetails(arg0 context.Context, arg1 uint64) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionDetails", arg0, arg1)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionDetails indicates an expected call of GetTransactionDetails.
func (mr *MockRepositoryMockRecorder) GetTransactionDetails(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionDetails", reflect.TypeOf((*MockRepository)(nil).GetTransactionDetails), arg0, arg1)
}

// GetTransactions mocks base method.
func (m *MockRepository) GetTransactions(arg0 context.Context, arg1 model.GetTransactionsParams) ([]model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", arg0, arg1)
	ret0, _ := ret[0].([]model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockRepositoryMockRecorder) GetTransactions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockRepository)(nil).GetTransactions), arg0, arg1)
}

// Transfer mocks base method.
func (m *MockRepository) Transfer(arg0 context.Context, arg1 model.TransferParams) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", arg0, arg1)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transfer indicates an expected call of Transfer.
func (mr *MockRepositoryMockRecorder) Transfer(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockRepository)(nil).Transfer), arg0, arg1)
}

// UpdateTransactionsStatus mocks base method.
func (m *MockRepository) UpdateTransactionsStatus(arg0 context.Context, arg1 uint64, arg2 model.TransactionStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionsStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionsStatus indicates an expected call of UpdateTransactionsStatus.
func (mr *MockRepositoryMockRecorder) UpdateTransactionsStatus(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionsStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionsStatus), arg0, arg1, arg2)
}

// Withdraw mocks base method.
func (m *MockRepository) Withdraw(arg0 context.Context, arg1 model.WithdrawParams) (model.TransactionDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", arg0, arg1)
	ret0, _ := ret[0].(model.TransactionDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockRepositoryMockRecorder) Withdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockRepository)(nil).Withdraw), arg0, arg1)
}

// MockAccountService is a mock of AccountService interface.
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
	isgomock struct{}
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService.
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance.
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockAccountService) GetBalance(ctx context.Context, userID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockAccountServiceMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockAccountService)(nil).GetBalance), ctx, userID)
}

// MockKafkaPublisher is a mock of KafkaPublisher interface.
type MockKafkaPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaPublisherMockRecorder
	isgomock struct{}
}

// MockKafkaPublisherMockRecorder is the mock recorder for MockKafkaPublisher.
type MockKafkaPublisherMockRecorder struct {
	mock *MockKafkaPublisher
}

// NewMockKafkaPublisher creates a new mock instance.
func NewMockKafkaPublisher(ctrl *gomock.Controller) *MockKafkaPublisher {
	mock := &MockKafkaPublisher{ctrl: ctrl}
	mock.recorder = &MockKafkaPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaPublisher) EXPECT() *MockKafkaPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockKafkaPublisher) Publish(ctx context.Context, topic, key string, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, topic, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockKafkaPublisherMockRecorder) Publish(ctx, topic, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockKafkaPublisher)(nil).Publish), ctx, topic, key, data)
}
